config/routes.rb
Rails.application.routes.draw do
  get 'payments/new'

  get 'reservations/index'

  get 'reservations/edit'

  get 'reservations/new'

  get 'reservations/show'

  get 'listing/index'

  get 'search', to: 'search#search'

  

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  resources :listings do
      resources :reservations do
 
      end
  end    

  end

  resources :users, only: [:show, :edit, :update, :destroy]     

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get '/tags/:tag', to: 'listings#tags', as: "tag"

  constraints Clearance::Constraints::SignedIn.new do
  root to: 'users#show', as: :signed_in_root
  end

  constraints Clearance::Constraints::SignedOut.new do
  root to: 'welcome#index'
  end

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :reservations do
    resources :payments, only: [:new, :create]
  end
  

end

app/models/listing.rb
require 'elasticsearch/model'

class Listing < ActiveRecord::Base

	include Elasticsearch::Model
	include Elasticsearch::Model::Callbacks

	belongs_to :user
	has_many :taggings 
	has_many :tags, through: :taggings, dependent: :destroy
	has_many :reservations
	has_one :payment

	mount_uploaders :places, PlaceUploader


	enum smoking: { No: '0', Yes: '1' }	

	def all_tags=(names)
  		self.tags = names.split(",").map do |name|
    	Tag.where(name: name.strip).first_or_create!
    	end
  	end


	def all_tags
  		self.tags.map(&:name).join(", ")
	end

	def self.tagged_with(name)
		Tag.find_by_name!(name).listings
	end

end
Listing.import force: true

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

 
  before_action :userid, except:[:tags]


  def index
  @listing = @user.listings.all
  @reservations = Reservation.all

  end
 
  def show
    @listing = Listing.find(params[:id])
    @reservations = @listing.reservations
 
  end
 
  def new
    @listing = @user.listings.build
  end
 
  def edit

    @listing = @user.listings.find(params[:id])
  end
 
  def create
    @listing = @user.listings.new(listing_params)
    @listing.all_tags = listing_params[:all_tags]
 
    if @listing.save
      redirect_to user_listings_path
    else
      render 'new'
    end
  end
 
  def update
    @listing = @user.listings.find(params[:id])
    if @listing.update(listing_params)
      redirect_to user_listings_path
    else
      render 'edit'
    end
  end
 
  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy
 
    redirect_to user_listings_path
  end

  def tags
    if params[:tag]
      @listings = Listing.tagged_with(params[:tag])
    end
  end
 
  
  private
    def userid 
      
      @user = User.find(params[:user_id])
    end
      
    def listing_params
      params.require(:listing).permit(:property_name, :address, :property_type, :rental,:price, :smoking, :gym, :internet, :tub, :all_tags, {places:[]})
    end
end

app/helpers/listing_helper.rb
module ListingHelper
	def tag_links(tags)
  	tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip) }.join(", ") 
	end
end

app/views/listings/_form.html.erb
<div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Place your listing here</h3>
        </div>
         <div class="panel-body">
         
<div class="property-field">
  <%= form.label :property_name, "Property Name:"%>
  <%= form.text_field :property_name %>
</div>

<div class="address-field">
  <%= form.label :address, "Address:" %>
  <%= form.text_area :address %>
</div>

<div class="type-field">
  <%= form.label :property_type, "Property Type:" %>
  <%= form.select :property_type, [['Landed', 'Landed'], ['Strata', 'Strata']] %>
</div>

<div class="rental-field">
  <%= form.label :rental, "Rental Type:" %>
  <%= form.select :rental, [['Whole Unit','W'],['Single Room', 'R'], ['Shared Room', 'S']] %>
</div>

<div class="rental-field">
  <%= form.label :price, "Price:" %>
  <%= form.text_field :price %>
</div>

<%= form.label :smoking, "Allow smoking in property:" %>
<%= form.check_box :smoking, value: "smoking" %>
<br>
<%= form.label :gym, "Gym facilities:" %>  
<%= form.check_box :gym, value: "gym" %>
<br>
<%= form.label :internet, "Internet:" %>
<%= form.check_box :internet, value: "internet" %>
<br>
<%= form.label :tub, "Hot Tub:" %>
<%= form.check_box :tub, value: "hot tub" %>

<%= form.label :all_tags, "Labels:" %>
<%= form.text_field :all_tags%>

<%= form.file_field :places, multiple: true %>

      <%= form.submit 'Go!', class:'btn btn-lg btn-default btn-block'%>
 

        </div>
      </div>
    </div>
  </div>
</div>

app/views/listings/_formreserve.html.erb
<%= f.label :check_in%> 
<%= f.date_field :check_in%>

<%= f.label :check_out%> 
<%= f.date_field :check_out%>

<%= f.submit 'Book Now!'%>

app/views/listings/edit.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>
<%= form_for [current_user,@listing] do |form| %>
    <%= render partial: '/listings/form', object: form %>

      
<!--     <%=link_to 'My_Listing ', user_listings_path(current_user)%>
 -->  <% end %>
</div>

app/views/listings/index.html.erb
<h1>Listings</h1>

<%@listing.each do |listing|%>
<%listing.places.each do |x|%>
  <%= image_tag x %>
<%end%>
<p> 
  <strong>Property Name:</strong>
  <%= listing.property_name %>
</p>
 
<p>
  <strong>Address:</strong>
  <%= listing.address %>
</p>

<p>
  <strong>Property Type:</strong>
  <%= listing.property_type %>
</p>

<p>
  <strong>Rental:</strong>
  <%= listing.rental %>
</p>

<p>
  <strong>Smoking Allowed:</strong>
  <%= listing.smoking %>
</p>

<p>
  <strong>Price per Night:</strong>
  <%= listing.price %>
</p>


<p>
  <strong>Label:</strong>
    <%=raw tag_links(listing.all_tags)%>
</p>



<%=link_to 'Edit This Listing ', edit_user_listing_path(current_user, listing)%>
<%=link_to 'Delete This Listing ', user_listing_path(current_user, listing), method: :delete%>
<%=link_to 'More Information ',user_listing_path(current_user, listing)%>
<%end%>

app/views/listings/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>
<%= form_for [current_user,@listing] do |form| %>
    <%= render partial: '/listings/form', object: form %>
<%= form.submit "Book now!!"%>
      
<!--     <%=link_to 'My_Listing ', user_listings_path(current_user)%>
 -->  <% end %>
</div>

app/views/listings/show.html.erb
<h1>Your Listing</h1>

  <strong>Property Name:</strong>
  <%= @listing.property_name %>
</p>
 
<p>
  <strong>Address:</strong>
  <%= @listing.address %>
</p>


<p>
  <strong>Property Type:</strong>
  <%= @listing.property_type %>
</p>

<p>
  <strong>Rental:</strong>
  <%= @listing.rental %>
</p>

<p>
  <strong>Smoking Allowed:</strong>
  <%= @listing.smoking %>
</p>

<p>
  <strong>Price per Night:</strong>
  <%= @listing.price %>
</p>

<p>
  <strong>Label:</strong>
  <%=raw tag_links(@listing.all_tags)%>
</p>


<h4 style="color:blue;">Book now</h4>
<%= form_for [current_user,@listing, Reservation.new] do |f| %>
    <%= f.label :check_in%> 
<%= f.date_field :check_in%>

<%= f.label :check_out%> 
<%= f.date_field :check_out%>

<%= f.submit 'Book Now!' %>
<%end%>


<%=link_to 'Edit This Listing ', edit_user_listing_path(current_user, @listing)%>
<%=link_to 'Delete This Listing ', user_listing_path(current_user, @listing), method: :delete%>

app/views/listings/tags.erb
<% @listings.each do |listing| %>
	<%= listing.property_name %>
	<%= listing.address %>
	<%= listing.property_type %>
	<%= raw tag_links(listing.all_tags) %>
<% end %>