config/routes.rb
Rails.application.routes.draw do
  get 'payments/new'

  get 'reservations/index'

  get 'reservations/edit'

  get 'reservations/new'

  get 'reservations/show'

  get 'listing/index'

  get 'search', to: 'search#search'

  

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  resources :listings do
      resources :reservations do
 
      end
  end    

  end

  resources :users, only: [:show, :edit, :update, :destroy]     

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get '/tags/:tag', to: 'listings#tags', as: "tag"

  constraints Clearance::Constraints::SignedIn.new do
  root to: 'users#show', as: :signed_in_root
  end

  constraints Clearance::Constraints::SignedOut.new do
  root to: 'welcome#index'
  end

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :reservations do
    resources :payments, only: [:new, :create]
  end
  

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

	def search
		if params[:q].nil?
			@listings =[]
		else
			@listings = Listing.search(params[:q]).records
		end
	end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/search.html.erb
<h1>Listings Search</h1>

<%= form_for search_path, method: :get do |f| %>
  <p>
    <%= f.label "Search for" %>
    <%= text_field_tag :q, params[:q] %>
    <%= submit_tag "Go", name: nil %>
  </p>
<% end %>

<ul>
  <% @listings.each do |listing| %>
    <li>
      <h3>
        <%= link_to "#{listing.property_name}",user_listing_path(current_user, listing)%>
      </h3>
    </li>
  <% end %>
</ul>