config/routes.rb
Rails.application.routes.draw do
  get 'payments/new'

  get 'reservations/index'

  get 'reservations/edit'

  get 'reservations/new'

  get 'reservations/show'

  get 'listing/index'

  get 'search', to: 'search#search'

  

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  resources :listings do
      resources :reservations do
 
      end
  end    

  end

  resources :users, only: [:show, :edit, :update, :destroy]     

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get '/tags/:tag', to: 'listings#tags', as: "tag"

  constraints Clearance::Constraints::SignedIn.new do
  root to: 'users#show', as: :signed_in_root
  end

  constraints Clearance::Constraints::SignedOut.new do
  root to: 'welcome#index'
  end

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :reservations do
    resources :payments, only: [:new, :create]
  end
  

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<h1>Welcome to PairBnb</h1>



<div class="container">
  <div class="jumbotron">
    <h1>Do You Know?</h1>      
    <p>People who who have more birthdays tend to live longer</p>
  </div>
  <p>Smile if you never knew</p>      
  <p>Smile still even though you have seen this else where.</p>
  <div class="submit-field">
		<%= link_to t(".sign_in"), sign_in_path, class: "btn btn-primary btn-md" %>
        <% if Clearance.configuration.allow_sign_up? %>
        <%= link_to t(".sign_up"), sign_up_path, class: "btn btn-primary btn-md" %>
        <% end %>         
	</div>      
</div>