config/routes.rb
Rails.application.routes.draw do
  get 'payments/new'

  get 'reservations/index'

  get 'reservations/edit'

  get 'reservations/new'

  get 'reservations/show'

  get 'listing/index'

  get 'search', to: 'search#search'

  

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  resources :listings do
      resources :reservations do
 
      end
  end    

  end

  resources :users, only: [:show, :edit, :update, :destroy]     

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get '/tags/:tag', to: 'listings#tags', as: "tag"

  constraints Clearance::Constraints::SignedIn.new do
  root to: 'users#show', as: :signed_in_root
  end

  constraints Clearance::Constraints::SignedOut.new do
  root to: 'welcome#index'
  end

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :reservations do
    resources :payments, only: [:new, :create]
  end
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <script src="https://js.braintreegateway.com/v2/braintree.js"></script>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="http://localhost:3000/">PairBnB</a>
      </div>
      <ul class="nav navbar-nav">
        <li class="active"><a href="http://localhost:3000/">Home</a></li>
        <li><%= link_to t(".my_Profile"), user_path(current_user) if signed_in? %></li>
        <li><%= link_to t(".my_Listing"), user_listings_path(current_user) if signed_in? %></li>  
        <li><%= link_to t(".create_Listing"), new_user_listing_path(current_user) if signed_in? %></li>
        <li><%= link_to t(".sign_Out"), sign_out_path, method: :delete if signed_in? %></li>
      </ul>
    </div>
  </nav>
  

  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>

  <%= yield %>
</body>
</html>